spring:
      datasource:
                driver-class-name: com.mysql.jdbc.Driver
                url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&serverTimezone=UTC
                username: <username>   
                password: <password>   
      jpa:
                hibernate.ddl-auto: update
                generate-ddl: true
                show-sql: true
